### ISSUE TITLE
Nonlinear PDEs on deforming domains

### ISSUE THREAD

**Issue by koehlerson** [SciML/PDEBase.jl#7]
In nonlinear continuum mechanics one has to seperate the reference domain $\Omega$ from the deformed domain $\Omega_t$. Thereby, one has to distinguish the gradients w.r.t. reference and deformed ("current") coordinates. For a short introduction see https://ferrite-fem.github.io/Ferrite.jl/stable/examples/hyperelasticity/#Introduction. In the example below the gradients are distinguished by `Grad` and `grad` where the capitalized version stands for the reference domain.  The first example uses a formulation based on the reference domain (in the sense of integrating over the reference domain, total Lagrangian approach) where P corresponds to the first Piola Kirchhoff stress.

```julia
using ModelingToolkit, SciMLBase
import Symbolics: ClosedInterval

@parameters X₁ x₁ f
@variables u(..) # should be u(X₁,x₁) ~ x₁ - X₁, X₁ in Ω and x₁ in deformed domain
Ω = ClosedInterval(0,1)

# TODO correct definitions.
grad(var) = Differential(x₁)(var)
Grad(var) = Differential(X₁)(var)
div(var) = Differential(x₁)(var)
Div(var) = Differential(X₁)(var)
P(Gradu) = .. # P is nonlinear stress (nonlinear generalized fluxes)

eqs = [Div(P(Grad(u)) ~ f]
bcs = [u(0.0) ~ 0., u(1.0) ~ 0.]

@named pde = PDESystem(eqs,bcs,[Ω],[X₁],[u(X₁,x₁)])

disc = MyFrameworkDiscretization(RitzGalerkin(...), TessellationInfo(...), MyFrameworkInfo(...))
prob = discretize(pdesys, disc, kwargs_to_prob...)
```

Another equivalent example uses the actual configuration, i.e. an updated Lagrangian approach

```julia
σ(gradu) = .. # Cauchy stress

eqs = [div(σ(grad(u)) ~ f]
bcs = [u(0.0) ~ 0., u(1.0) ~ 0.]

@named pde = PDESystem(eqs,bcs,[Ω],[x₁],[u(X₁,x₁)]) # Now, Ω needs to hold x₁, i.e. x₁ = X₁ + u

disc = MyFrameworkDiscretization(RitzGalerkin(...), TessellationInfo(...), MyFrameworkInfo(...))
prob = discretize(pdesys, disc, kwargs_to_prob...)
```

**Comment by koehlerson** [comment]
I think both should be supported since you have very different applications in both cases. What I mean by this is that there are formulations where updated Lagrangians are more favorable than total Lagrangians and vice versa

**Comment by xtalax** [comment]
The systems you have written could also be handled by MOL at present, so we can leave both these syntaxes as supported, looks good!
